Repository chainguard-dev/edu, pull requests merged in 2022-11, with the labels that each got.

#179 Add Enforce OpenAPI Specification to the site (#178)
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/api/index.md
  static/api.json
Labels: documentation, enhancement

#182 Adding global CSP rules
  layouts/partials/head/script-header.html
Labels: enhancement

#187 Add Enforce Events page
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-events/index.md
Labels: documentation

#190 Fixed CSP rule for analytics
  layouts/partials/head/script-header.html
Labels: bug

#191 Create cloud-run.yaml
  .github/workflows/cloud-run.yaml
  Dockerfile
  nginx.conf
Labels: enhancement

#192 Add try_files directive to nginx.conf to fix invalid redirects
  nginx.conf
Labels: bug
