Repository chainguard-dev/edu, pull requests merged in 2022-12, with the labels that each got.

#204 Update: UI instructions
  content/ui/group.md
  content/ui/install.md
  content/ui/policy.md
Labels: documentation

#205 Feature: document the `cluster-{name,description}` fields.
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/alternative-installation-methods.md
Labels: documentation

#206 update chainctl install instructions
  content/chainguard/chainguard-enforce/chainctl-docs/how-to-install-chainctl.md
Labels: bug

#208 Update the step verification to use intermediate fulcio cert
  content/open-source/sigstore/fulcio/how-to-inspect-and-verify-fulcio-certificates.md
Labels: bug

#211 Add Enforce/chainctl changelog page
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/changelog.md
Labels: documentation

#207 Update chainctl docs
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-user-onboarding.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/how-to-install-chainctl.md
Labels: documentation

#212 Add 301 redirect for how-to-install-chainctl
  content/chainguard/chainguard-enforce/how-to-install-chainctl.md
  nginx.conf
Labels: bug

#220 Fix port in redirected URLs, move rewrites to a map
  nginx.conf
Labels: bug, documentation

#226 Add one-liner showing how to verify chainctl binary with cosign
  content/chainguard/chainguard-enforce/how-to-install-chainctl.md
Labels: documentation, enforce

#237 Add pages on verifying blob signatures with cosign or rekor-cli
  content/open-source/sigstore/cosign/how-to-verify-file-signatures-with-cosign.md
  content/open-source/sigstore/rekor/how-to-verify-file-signatures-with-rekor-or-curl.md
Labels: documentation, open source
