Repository chainguard-dev/edu, pull requests merged in 2022-10, with the labels that each got.

#151 fix: remove warning when applying policy
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-policy-examples.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-user-onboarding.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/connecting-to-private-registries.md
Labels: documentation

#152 Fixing Netlify Deploy Preview
  config/_default/config.toml
  netlify.toml
Labels: bug

#158 Updating apko docs
  content/open-source/apko/faq.md
  content/open-source/apko/getting-started-with-apko.md
  content/open-source/apko/overview/apko_melange_ecosystem.png
  content/open-source/apko/overview/index.md
  content/open-source/apko/reference.md
Labels: documentation, enhancement

#150 Add terminal back to melange getting started guide
  content/open-source/melange/getting-started-with-melange.md
Labels: bug, documentation
