Repository chainguard-dev/edu, pull requests merged in 2023-05, with the labels that each got.

#648 Re-enable terminal
  layouts/article/single.html
Labels: bug

#656 Update URLs in tutorials
  content/chainguard/chainctl/_index.md
  content/chainguard/chainguard-enforce/administration/connecting-to-private-registries.md
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-github/getting-started-enforce-github/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-signing/getting-started-chainguard-enforce-signing.md
  content/chainguard/chainguard-enforce/chainguard-enforce-user-onboarding.md
  content/chainguard/chainguard-enforce/cloudevents/create-github-issues/index.md
  content/chainguard/chainguard-enforce/cloudevents/create-jira-issues/index.md
  content/chainguard/chainguard-enforce/cloudevents/create-slack-alerts/index.md
  content/chainguard/chainguard-enforce/concepts/detect-log4shell-demo/index.md
  content/chainguard/chainguard-enforce/concepts/gulfstream-overview/index.md
  content/chainguard/chainguard-enforce/enforce-overview/index.md
  content/chainguard/chainguard-enforce/how-to-connect-kubernetes-clusters.md
  content/chainguard/chainguard-enforce/installation/alternative-installation-methods.md
  content/chainguard/chainguard-enforce/installation/profiles/index.md
  content/chainguard/chainguard-enforce/policies/chainguard-enforce-policy-examples.md
  content/chainguard/chainguard-enforce/policies/chainguard-policies-cli.md
  content/chainguard/chainguard-enforce/policies/chainguard-policies-ui/index.md
  content/chainguard/chainguard-enforce/policies/other-policies/critical-cve-policy.md
  content/chainguard/chainguard-enforce/policies/other-policies/k8s-registry-deprecation-policy.md
  content/chainguard/chainguard-enforce/policies/other-policies/maximum-image-age-policy.md
  content/open-source/apko/getting-started-with-apko.md
  content/open-source/melange/tutorials/getting-started-with-melange.md
  content/open-source/oci/what-are-oci-artifacts.md
  content/open-source/oci/what-is-the-oci.md
  content/open-source/sbom/getting-started-openvex-vexctl.md
  content/open-source/sbom/what-is-an-sbom.md
  content/open-source/sbom/what-is-openvex.md
  content/open-source/sbom/what-makes-a-good-sbom.md
  content/open-source/sigstore/_index.md
  content/open-source/sigstore/cosign/an-introduction-to-cosign.md
  content/open-source/sigstore/cosign/how-to-sign-an-sbom-with-cosign.md
  content/open-source/sigstore/cosign/how-to-sign-blobs-with-cosign.md
  content/open-source/sigstore/fulcio/how-to-generate-a-fulcio-certificate.md
  content/open-source/sigstore/fulcio/how-to-inspect-and-verify-fulcio-certificates.md
  content/open-source/sigstore/how-to-keyless-sign-a-container-with-sigstore/index.md
  content/open-source/sigstore/policy-controller/disallowing-non-default-capabilities-with-policy-controller.md
  content/open-source/sigstore/policy-controller/disallowing-privileged-containers-with-policy-controller.md
  content/open-source/sigstore/policy-controller/disallowing-run-as-root-user-with-policy-controller.md
  content/open-source/sigstore/policy-controller/disallowing-unsafe-sysctls-with-policy-controller.md
  content/open-source/sigstore/policy-controller/enforce-sbom-attestation-with-policy-controller.md
  content/open-source/sigstore/policy-controller/how-to-install-policy-controller.md
  content/open-source/sigstore/policy-controller/maximum-image-age-policy-controller.md
  content/open-source/sigstore/policy-controller/using-policy-controller-to-verify-signed-chainguard-images.md
  content/open-source/sigstore/policy-controller/warn-deprecated-k8s-registry.md
  content/open-source/sigstore/rekor/how-to-query-rekor.md
  content/open-source/sigstore/rekor/how-to-sign-and-upload-metadata-to-rekor.md
  content/open-source/sigstore/rekor/how-to-verify-file-signatures-with-rekor-or-curl.md
  content/open-source/slsa/what-is-slsa.md
  content/open-source/wolfi/wolfi-with-dockerfiles.md
  content/software-security/selecting-a-base-image.md
  content/ui/prerequisites.md
Labels: documentation, enhancement, platform development

#654 Enable hugo aliases - doks turns them off by default
  config/_default/config.toml
Labels: bug, platform development

#668 Update nginx.conf with 404.html page; incorporate upstream image changes
  Dockerfile
  nginx.conf
Labels: bug, platform development

#676 Update enforce events page with registry cloudevents
  content/chainguard/chainguard-enforce/reference/events.md
Labels: documentation, enforce

#666 chainlink checking tool
  .github/workflows/check-links.yaml
  tools/chainlink/README.md
  tools/chainlink/files.go
  tools/chainlink/go.mod
  tools/chainlink/go.sum
  tools/chainlink/html.go
  tools/chainlink/ignore.go
  tools/chainlink/ignore.json
  tools/chainlink/links.go
  tools/chainlink/main.go
  tools/chainlink/markdown.go
  tools/chainlink/results.go
  tools/chainlink/types.go
Labels: platform development

#670 adding guides on Assumed Identities and GitHub Identity federation
  content/chainguard/chainguard-enforce/authentication/custom-idps/index.md
  content/chainguard/chainguard-enforce/iam-groups/assumable-ids.md
  content/chainguard/chainguard-enforce/iam-groups/enforce-github-identity/actions-new-workflow.png
  content/chainguard/chainguard-enforce/iam-groups/enforce-github-identity/actions-run-workflow.png
  content/chainguard/chainguard-enforce/iam-groups/enforce-github-identity/actions-workflow-output.png
  content/chainguard/chainguard-enforce/iam-groups/enforce-github-identity/index.md
Labels: documentation, enforce

#689 Detect theme and pass color-scheme query param to embedded terminal
  assets/js/terminal.js
Labels: enhancement, platform development

#696 Add images network requirements page
  content/chainguard/chainguard-images/network-requirements.md
  content/chainguard/chainguard-images/registry/overview.md
Labels: documentation, images

#701 turn off emojis
  config/_default/config.toml
Labels: enhancement

#709 Buildkite assumable ID example plus tweaks to current ID docs
  content/chainguard/chainguard-enforce/authentication/custom-idps/index.md
  content/chainguard/chainguard-enforce/iam-groups/assumable-ids.md
  content/chainguard/chainguard-enforce/iam-groups/identity-examples/_index.md
  content/chainguard/chainguard-enforce/iam-groups/identity-examples/enforce-buildkite-identity.md
  content/chainguard/chainguard-enforce/iam-groups/identity-examples/enforce-github-identity/actions-new-workflow.png
  content/chainguard/chainguard-enforce/iam-groups/identity-examples/enforce-github-identity/actions-run-workflow.png
  content/chainguard/chainguard-enforce/iam-groups/identity-examples/enforce-github-identity/actions-workflow-output.png
  content/chainguard/chainguard-enforce/iam-groups/identity-examples/enforce-github-identity/index.md
Labels: documentation, enforce

#717 Add Jenkins assumable identities tutorial, and rudimentary inline %variable% editing
  assets/js/replacer.js
  assets/scss/replacer.scss
  content/chainguard/chainguard-enforce/iam-groups/identity-examples/enforce-jenkins-identity/index.md
  content/chainguard/chainguard-enforce/iam-groups/identity-examples/enforce-jenkins-identity/jenkins-job-parameter.png
  content/chainguard/chainguard-enforce/iam-groups/identity-examples/enforce-jenkins-identity/jenkins-oidc-connect-config.png
  content/chainguard/chainguard-enforce/iam-groups/identity-examples/enforce-jenkins-identity/jenkins-oidc-credential.png
  layouts/article/single.html
  layouts/partials/replacer.html
Labels: documentation, platform development

#714 Add enforce-bitbucket assumed identities tutorial
  content/chainguard/chainguard-enforce/iam-groups/identity-examples/enforce-bitbucket-identity.md
Labels: documentation, enforce

#735 Adding missing JS for rumble graphs in images compared page
  assets/js/rumble.js
  layouts/shortcodes/rumble.html
Labels: bug, images

#734 Adding guide on how to use tag history api
  content/chainguard/chainguard-images/using-the-tag-history-api.md
Labels: documentation, images
