Repository chainguard-dev/edu, pull requests merged in 2023-10, with the labels that each got.

#1041 adding Considerations for Keeping Images Up to Date conceptual
  content/software-security/secure-software-development/considerations-for-image-updates.md
Labels: documentation

#1053 Update building-a-wolfi-package.md to fix broken link to php
  content/open-source/wolfi/building-a-wolfi-package.md
Labels: Q4 2023 Project, hacktoberfest-accepted

#1060 Moving 'Considerations for Keeping Images Up to Date' to Images bucket
  content/chainguard/chainguard-images/considerations-for-image-updates.md
  nginx.conf
Labels: documentation, q422

#1067 Enhancement: Position menu with active navigation item
  assets/js/index.js
  layouts/partials/footer/script-footer.html
Labels: enhancement

#1073 Add note to vulnerability comparison pages about scanner false matches
  layouts/partials/rumble-comparison.html
Labels: documentation, Q4 2023 Project
