Repository chainguard-dev/edu, pull requests merged in 2023-03, with the labels that each got.

#419 Update README.md with list of available terminal images
  README.md
Labels: documentation, terminal

#442 Enforce signing: recommend using cosign v2
  content/chainguard/chainguard-enforce/chainguard-enforce-signing/getting-started-chainguard-enforce-signing.md
  content/open-source/sigstore/cosign/how-to-install-cosign.md
  content/open-source/sigstore/policy-controller/maximum-image-age-policy-controller.md
Labels: documentation, enforce, open source

#418 Add policy-controller tutorial about unsafe sysctls
  content/open-source/sigstore/policy-controller/disallowing-unsafe-sysctls-with-policy-controller.md
Labels: documentation, policy controller initiative

#425 Add images-demos terminal image and update readme
  README.md
  terminal-images/academy-base/Dockerfile
  terminal-images/images-demos/Dockerfile
Labels: documentation, terminal

#421 Add policy-controller tutorial about running as non-root user
  content/open-source/sigstore/policy-controller/disallowing-run-as-root-user-with-policy-controller.md
Labels: documentation, terminal, policy controller initiative

#427 Add policy-controller tutorial about running with non-default capabilities
  content/open-source/sigstore/policy-controller/disallowing-non-default-capabilities-with-policy-controller.md
Labels: documentation, terminal, policy controller initiative

#426 Add policy-controller tutorial about running unprivileged pods
  content/open-source/sigstore/policy-controller/disallowing-privileged-containers-with-policy-controller.md
Labels: documentation, terminal, policy controller initiative

#445 enforce-signing: Add section with an enforce signing policy
  content/chainguard/chainguard-enforce/chainguard-enforce-signing/getting-started-chainguard-enforce-signing.md
  content/chainguard/chainguard-enforce/chainguard-enforce-signing/verify-enforce-signed-images.md
Labels: sig-aas

#439 Caa UI update
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/cloud-account-associations.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/cloud-account-associations/gcp_step2.png
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/cloud-account-associations/gcp_step3.png
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/cloud-account-associations/gcp_step4.png
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/cloud-account-associations/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/cloud-account-associations/settings-grp-selection.png
Labels: documentation, enhancement, enforce

#467 Add note about registry access for Enforce SaaS to network reqs page
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/network-requirements.md
Labels: documentation, enforce

#472 Add cloud-native software supply chain security definition
  content/software-security/what-is-software-supply-chain-security.md
Labels: documentation, enhancement

#480 Switch academy/apko image to use melange and apko
  content/open-source/apko/getting-started-with-apko.md
  terminal-images/apko/Dockerfile
  terminal-images/apko/apko.yaml
  terminal-images/apko/melange.yaml
  terminal-images/apko/profile.sh
Labels: documentation, platform development, terminal

#481 Fix melange broken links
  content/chainguard/chainguard-images/how-to-use-chainguard-images.md
  content/open-source/apko/troubleshooting.md
Labels: bug

#482 Adjusting tags text in ReadMe
  README.md
Labels: documentation

#499 Enforce GitHub signing
  .chainguard/source.yaml
Labels: enhancement, platform development

#506 Add css font-size rules for code elements in headers
  assets/scss/common/_custom.scss
Labels: platform development

#485 Adding tags to Enforce docs
  content/chainguard/chainguard-enforce/chainguard-enforce-github/getting-started-enforce-github/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/alternative-installation-methods.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/annotation-based-caching.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-discovery-onboarding/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-events/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-policy-examples.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-rego-policies.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-user-onboarding.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-policies-cli.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-policies-ui/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/cloud-account-associations/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/connecting-to-private-registries.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/detect-log4shell-demo/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/enforce-overview/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/how-to-connect-kubernetes-clusters.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/how-to-disable-policy-enforcement.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/how-to-manage-iam-groups-in-chainguard-enforce.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/log-in-chainguard-enforce/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/network-requirements.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/overview-of-enforce-iam-model.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/troubleshooting-tips.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/understanding-continuous-verification.md
  content/chainguard/chainguard-enforce/chainguard-enforce-signing/chainguard-enforce-signing-faqs.md
  content/chainguard/chainguard-enforce/chainguard-enforce-signing/enforce-signing-setup.md
  content/chainguard/chainguard-enforce/chainguard-enforce-signing/getting-started-chainguard-enforce-signing.md
  content/chainguard/chainguard-enforce/chainguard-enforce-signing/verify-enforce-signed-images.md
  content/chainguard/chainguard-enforce/how-to-install-chainctl.md
  content/chainguard/chainguard-images/faq.md
  content/chainguard/chainguard-images/how-to-use-chainguard-images.md
  content/chainguard/chainguard-images/images-compared.md
  content/chainguard/chainguard-images/overview.md
Labels: documentation

#504 Enforce agent install requirements
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/installation-requirements.md
Labels: documentation, enforce

#517 update cosign instructions to verify chainctl
  content/chainguard/chainguard-enforce/how-to-install-chainctl.md
Labels: bug, documentation

#515 adding draft on Chainguard Enforce profiles
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/profiles/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/profiles/profiles_console.png
Labels: documentation, enforce

#518 Fix #405: make nav elements clickable with embedded terminal
  assets/scss/terminal.scss
Labels: bug, platform development

#523 Add partial to render data/notices.yaml for any page that needs a notice
  assets/scss/common/_custom.scss
  data/notices.yaml
  layouts/article/single.html
  layouts/partials/notice.html
Labels: platform development

#484 Adding tags to chainctl content
  .github/workflows/integrate-enforce-docs/action.yaml
Labels: documentation

#531 Fix missing quote in integrate Enforce action
  .github/workflows/integrate-enforce-docs/action.yaml
Labels: bug, platform development, automated

#532 Revert "Fix missing quote in integrate Enforce action"
  .github/workflows/integrate-enforce-docs/action.yaml
Labels: bug

#529 Update UX docs
  content/ui/group.md
  content/ui/inspect.md
  content/ui/policy.md
Labels: documentation

#535 Add tags for enforce changelog, events, and fix chainctl tags *again*
  .github/workflows/integrate-enforce-docs/action.yaml
Labels: documentation, automated

#519 docs: explain the enforcer_options
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/configure-enforcer-options-during-installation.md
Labels: enforce

#538 Update COSIGN_EXPERIMENTAL everywhere to v2
  content/open-source/sigstore/cosign/how-to-verify-file-signatures-with-cosign.md
  content/open-source/sigstore/fulcio/how-to-generate-a-fulcio-certificate.md
  content/open-source/sigstore/fulcio/how-to-inspect-and-verify-fulcio-certificates.md
  content/open-source/sigstore/how-to-keyless-sign-a-container-with-sigstore/index.md
  content/open-source/sigstore/rekor/install-a-rekor-instance.md
Labels: documentation

#530 Fix notice partial and css rules with working class names
  assets/scss/common/_custom.scss
  layouts/partials/notice.html
Labels: bug, platform development

#549 Fix typo
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/understanding-continuous-verification.md
Labels: documentation
