Repository chainguard-dev/edu, pull requests merged in 2023-01, with the labels that each got.

#247 Add initial draft of sbom quality section
  content/software-security/what-makes-a-good-sbom.md
Labels: documentation, enhancement

#248 Change menu link
  config/_default/params.toml
  layouts/partials/header/header.html
Labels: platform development

#255 Fix "What Makes a Good SBOM?" Page Not Showing Up
  config/_default/menus/menus.en.toml
  content/open-source/sbom/what-makes-a-good-sbom.md
Labels: bug, documentation, open source

#266 Headless login added to signing in documentation for Enforce
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/log-in-chainguard-enforce/device-activation-chainguard.png
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/log-in-chainguard-enforce/index.md
Labels: documentation

#275 Add terminal back to apko, cosign, and rekor pages
  content/open-source/apko/getting-started-with-apko.md
  content/open-source/sigstore/cosign/how-to-sign-a-container-with-cosign.md
  content/open-source/sigstore/rekor/how-to-query-rekor.md
  content/open-source/sigstore/rekor/how-to-sign-and-upload-metadata-to-rekor.md
Labels: documentation, enhancement

#279 Feature: Document the need to instantiate regional AWS audit logs.
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/cloud-account-associations.md
Labels: documentation, enhancement, enforce

#277 Add Dockerfiles for interactive terminal images
  terminal-images/README.md
  terminal-images/academy-base/Dockerfile
  terminal-images/apko/Dockerfile
  terminal-images/cosign/Dockerfile
  terminal-images/rekor/Dockerfile
Labels: documentation, enhancement

#270 PHP Chainguard Image Guide
  content/chainguard/chainguard-images/reference/php/getting-started.md
  content/chainguard/chainguard-images/reference/php/overview.md
Labels: images

#280 Update enforce changelog
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/changelog.md
Labels: documentation, enforce

#227 Add integrate-docs github action
  .github/workflows/autodocs-enforce.yaml
  .github/workflows/deploy.yaml
  .github/workflows/integrate-enforce-docs/action.yaml
Labels: documentation, enhancement, platform development

#290 Add github token to autodocs-enforce action
  .github/workflows/autodocs-enforce.yaml
Labels: bug

#291 Add pull-request permission for autodocs-enforce gh token
  .github/workflows/autodocs-enforce.yaml
Labels: bug

#276 Add terminal to how-to-use-chainguard-images page
  content/chainguard/chainguard-images/how-to-use-chainguard-images.md
Labels: documentation, enhancement

#308 fix chainctl curl command
  content/ui/install.md
Labels: documentation

#307 Added sbom index and what is sbom article
  config/_default/menus/menus.en.toml
  content/open-source/sbom/_index.md
  content/open-source/sbom/what-is-an-sbom.md
Labels: documentation

#316 Minor revisions based on John Speed's feedback
  content/open-source/sbom/what-is-an-sbom.md
Labels: documentation

#321 Disable terminal while backend is being repaired
  layouts/partials/terminal.html
Labels: bug, documentation, platform development

#319 Add Enforce network requirements page
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/network-requirements.md
Labels: documentation, enforce

#309 adding Getting Started with Enforce Discovery doc, also playing with …
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chaingaurd-enforce-discovery-onboarding.md
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/cloud-account-associations.md
Labels: enhancement

#324 Reenable terminal
  layouts/partials/terminal.html
Labels: platform development
