Repository chainguard-dev/edu, pull requests merged in 2023-09, with the labels that each got.

#958 Add quickstart for Wolfi.
  content/open-source/wolfi/overview.md
Labels: documentation

#974 Images updates, architecture guidance
  content/chainguard/chainguard-images/how-to-use-chainguard-images.md
  content/chainguard/chainguard-images/overview.md
Labels: Q3 2023 Project

#976 chainctl images diff documentation
  content/chainguard/chainguard-images/comparing-images.md
  content/chainguard/chainguard-images/images-compared.md
  nginx.conf
Labels: documentation, images
