Repository chainguard-dev/edu, pull requests merged in 2023-11, with the labels that each got.

#1102 Update Getting Started for Python image for clarity
  content/chainguard/chainguard-images/getting-started/getting-started-python.md
Labels: documentation, images

#986 Remove reference to gcc-musl
  content/chainguard/chainguard-images/how-to-use-chainguard-images.md
Labels: Q3 2023 Project

#1126 moving Events ref doc + removing enforce Admin bucket
  .github/workflows/integrate-enforce-docs/action.yaml
  content/chainguard/chainguard-enforce/administration/_index.md
  content/chainguard/chainguard-enforce/annotation-based-caching.md
  content/chainguard/chainguard-enforce/authentication/connecting-to-private-registries.md
  content/chainguard/chainguard-enforce/authentication/identity-examples/_index.md
  nginx.conf
Labels: documentation, Q4 2023 Project

#1140 fixing actions doc to finalize events reference move
  .github/workflows/integrate-enforce-docs/action.yaml
  content/chainguard/administration/cloudevents/events-reference.md
  content/chainguard/chainguard-enforce/reference/events.md
Labels: documentation

#1143 adding how to minimize CVE risk doc + zero-day glossary entry
  content/chainguard/chainguard-images/cve-risk.md
  content/software-security/glossary.md
Labels: documentation, Q4 2023 Project, images

#1151 add images to the container images tutorial
  content/software-security/what-are-containers/container_structure.png
  content/software-security/what-are-containers/image_to_container.png
Labels: documentation, Q4 2023 Project

#1149 adding Doc on retrieving Image SBOMs
  content/chainguard/chainguard-images/retrieve-image-sboms.md
Labels: documentation, Q4 2023 Project

#1169 Improving images listing in reference docs
  assets/scss/common/_custom.scss
  content/chainguard/chainguard-images/reference/_index.md
  layouts/article/list-images.html
Labels: images, platform development

#1183 removing outdated Image Reference docs
  content/chainguard/chainguard-images/reference/external-attacher/_index.md
  content/chainguard/chainguard-images/reference/external-attacher/image_specs.md
  content/chainguard/chainguard-images/reference/external-attacher/provenance_info.md
  content/chainguard/chainguard-images/reference/external-attacher/tags_history.md
  content/chainguard/chainguard-images/reference/external-resizer/_index.md
  content/chainguard/chainguard-images/reference/external-resizer/image_specs.md
  content/chainguard/chainguard-images/reference/external-resizer/provenance_info.md
  content/chainguard/chainguard-images/reference/external-resizer/tags_history.md
  content/chainguard/chainguard-images/reference/oidc-discovery-provider/_index.md
  content/chainguard/chainguard-images/reference/oidc-discovery-provider/image_specs.md
  content/chainguard/chainguard-images/reference/oidc-discovery-provider/provenance_info.md
  content/chainguard/chainguard-images/reference/oidc-discovery-provider/tags_history.md
  nginx.conf
Labels: documentation, images, readme
