Repository chainguard-dev/edu, pull requests merged in 2023-04, with the labels that each got.

#566 Add gitsign to enforce github actions
  .github/workflows/autodocs-enforce.yaml
Labels: documentation, platform development

#562 enforcer options: add namespace enforcement mode new option
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/configure-enforcer-options-during-installation.md
Labels: documentation

#570 Update tutorials with terminals to use melange+apko signed images
  README.md
  content/open-source/apko/getting-started-with-apko.md
  content/open-source/melange/tutorials/getting-started-with-melange.md
  content/open-source/sbom/getting-started-openvex-vexctl.md
  content/open-source/sigstore/cosign/how-to-sign-a-container-with-cosign.md
  content/open-source/sigstore/policy-controller/disallowing-non-default-capabilities-with-policy-controller.md
  content/open-source/sigstore/policy-controller/disallowing-privileged-containers-with-policy-controller.md
  content/open-source/sigstore/policy-controller/disallowing-run-as-root-user-with-policy-controller.md
  content/open-source/sigstore/policy-controller/disallowing-unsafe-sysctls-with-policy-controller.md
  content/open-source/sigstore/policy-controller/enforce-sbom-attestation-with-policy-controller.md
  content/open-source/sigstore/policy-controller/how-to-install-policy-controller.md
  content/open-source/sigstore/policy-controller/maximum-image-age-policy-controller.md
  content/open-source/sigstore/policy-controller/using-policy-controller-to-verify-signed-chainguard-images.md
  content/open-source/sigstore/policy-controller/warn-deprecated-k8s-registry.md
  content/open-source/sigstore/rekor/how-to-query-rekor.md
  content/open-source/sigstore/rekor/how-to-sign-and-upload-metadata-to-rekor.md
Labels: terminal

#571 Add list of Google Cloud and AWS resources that Enforce creates
  content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/cloud-account-associations/index.md
Labels: documentation, enforce

#584 Sign images autodocs
  .github/workflows/autodocs-images.yaml
Labels: platform development

#588 Update autodocs-images.yaml
  .github/workflows/autodocs-images.yaml
Labels: platform development

#590 update with pull token details
  content/chainguard/chainguard-images/registry/authenticating.md
Labels: documentation

#591 update chainctl identity command
  content/chainguard/chainguard-images/registry/authenticating.md
Labels: documentation

#615 Copy layouts/index.redirects from doks theme
  layouts/index.redirects
Labels: bug, platform development

#614 Run Enforce docs on a schedule, only when there is a release
  .github/workflows/autodocs-enforce.yaml
Labels: enhancement, automated

#606 Add tutorial on creating github issues from enforce cloudevents
  .github/workflows/integrate-enforce-docs/action.yaml
  content/chainguard/chainguard-enforce/events/_index.md
  content/chainguard/chainguard-enforce/events/create-github-issues/github-issue.png
  content/chainguard/chainguard-enforce/events/create-github-issues/google-cloud-logs.png
  content/chainguard/chainguard-enforce/events/create-github-issues/index.md
  content/chainguard/chainguard-enforce/reference/events.md
  nginx.conf
Labels: documentation, enforce

#609 Adding data collection reference doc
  content/chainguard/chainguard-enforce/reference/data-collection.md
Labels: documentation, enforce

#607 Add tutorial on creating slack messages from enforce cloudevents
  content/chainguard/chainguard-enforce/events/create-github-issues/index.md
  content/chainguard/chainguard-enforce/events/create-slack-alerts/index.md
  content/chainguard/chainguard-enforce/events/create-slack-alerts/slack-admission-message.png
Labels: documentation, enforce

#628 Add data/notices.yaml warning about nginx image breaking changes
  data/notices.yaml
Labels: documentation

#625 adding Nathan's SSO/Custom IDP docs
  content/chainguard/chainguard-enforce/authentication/_index.md
  content/chainguard/chainguard-enforce/authentication/custom-idps/index.md
  content/chainguard/chainguard-enforce/authentication/custom-idps/sso-1.png
  content/chainguard/chainguard-enforce/authentication/custom-idps/sso-2.png
  content/chainguard/chainguard-enforce/authentication/example-idps/_index.md
  content/chainguard/chainguard-enforce/authentication/example-idps/azure-ad/aad-1.png
  content/chainguard/chainguard-enforce/authentication/example-idps/azure-ad/aad-2.png
  content/chainguard/chainguard-enforce/authentication/example-idps/azure-ad/aad-3-new-reg-less-wide.png
  content/chainguard/chainguard-enforce/authentication/example-idps/azure-ad/aad-6.png
  content/chainguard/chainguard-enforce/authentication/example-idps/azure-ad/aad-7.png
  content/chainguard/chainguard-enforce/authentication/example-idps/azure-ad/aad-8.png
  content/chainguard/chainguard-enforce/authentication/example-idps/azure-ad/aad-branding.png
  content/chainguard/chainguard-enforce/authentication/example-idps/azure-ad/index.md
  content/chainguard/chainguard-enforce/authentication/example-idps/okta/index.md
  content/chainguard/chainguard-enforce/authentication/example-idps/okta/okta-1.png
  content/chainguard/chainguard-enforce/authentication/example-idps/okta/okta-4-5.png
  content/chainguard/chainguard-enforce/authentication/example-idps/okta/okta_2_create_buttons.png
  content/chainguard/chainguard-enforce/authentication/example-idps/okta/okta_3_new-web-app-int.png
  content/chainguard/chainguard-enforce/authentication/example-idps/okta/okta_6_open_id_connect-2.png
  content/chainguard/chainguard-enforce/authentication/example-idps/ping-id/index.md
  content/chainguard/chainguard-enforce/authentication/example-idps/ping-id/ping-1.png
  content/chainguard/chainguard-enforce/authentication/example-idps/ping-id/ping-2-add-app.png
  content/chainguard/chainguard-enforce/authentication/example-idps/ping-id/ping-3.png
  content/chainguard/chainguard-enforce/authentication/example-idps/ping-id/ping-4.png
  content/chainguard/chainguard-enforce/authentication/example-idps/ping-id/ping-7-edit-conf.png
  content/chainguard/chainguard-enforce/authentication/example-idps/ping-id/ping-8-2.png
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/authorize-chainguard-enforce-gitlab.png
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/chainctl-auth-successful.png
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/chainguard-enforce-console-landing-page.png
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/console-sign-in.png
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/device-activation-chainguard.png
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/index.md
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/log-in-with-chainctl.png
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/sign-in-with-github.png
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/sign-in-with-gitlab.jpg
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/sign-in-with-google.png
Labels: documentation, enforce

#639 Update incorrect URLs in tutorials
  content/chainguard/chainguard-enforce/chainguard-enforce-discovery-onboarding/index.md
  content/chainguard/chainguard-enforce/chainguard-enforce-signing/getting-started-chainguard-enforce-signing.md
  content/chainguard/chainguard-enforce/chainguard-enforce-user-onboarding.md
  content/chainguard/chainguard-enforce/cloud-account-associations/index.md
  content/chainguard/chainguard-enforce/concepts/detect-log4shell-demo/index.md
  content/chainguard/chainguard-enforce/installation/alternative-installation-methods.md
  content/chainguard/chainguard-enforce/policies/chainguard-policies-cli.md
  content/chainguard/chainguard-enforce/policies/chainguard-policies-ui/index.md
  content/chainguard/chainguard-enforce/policies/how-to-disable-policy-enforcement.md
  content/chainguard/chainguard-enforce/policies/other-policies/critical-cve-policy.md
  content/chainguard/chainguard-enforce/policies/other-policies/k8s-registry-deprecation-policy.md
  content/chainguard/chainguard-enforce/policies/other-policies/maximum-image-age-policy.md
  content/chainguard/chainguard-enforce/reference/configure-enforcer-options-during-installation.md
  content/chainguard/chainguard-enforce/reference/installation-requirements.md
  content/chainguard/chainguard-enforce/troubleshooting-tips.md
  content/ui/enforce.md
  nginx.conf
Labels: bug, documentation, platform development

#640 Add nginx redirects for stale incoming urls
  content/chainguard/chainguard-enforce/authentication/log-in-chainguard-enforce/index.md
  content/chainguard/chainguard-enforce/enforce-overview/index.md
  content/chainguard/chainguard-enforce/policies/chainguard-policies-cli.md
  content/chainguard/chainguard-enforce/policies/chainguard-policies-ui/index.md
  content/chainguard/chainguard-enforce/reference/installation-requirements.md
  nginx.conf
Labels: bug, platform development

#623 Add tutorial on creating jira issues from enforce events
  content/chainguard/chainguard-enforce/cloudevents/_index.md
  content/chainguard/chainguard-enforce/cloudevents/create-github-issues/github-issue.png
  content/chainguard/chainguard-enforce/cloudevents/create-github-issues/google-cloud-logs.png
  content/chainguard/chainguard-enforce/cloudevents/create-github-issues/index.md
  content/chainguard/chainguard-enforce/cloudevents/create-jira-issues/google-cloud-logs.png
  content/chainguard/chainguard-enforce/cloudevents/create-jira-issues/index.md
  content/chainguard/chainguard-enforce/cloudevents/create-jira-issues/jira-issue.png
  content/chainguard/chainguard-enforce/cloudevents/create-slack-alerts/index.md
  content/chainguard/chainguard-enforce/cloudevents/create-slack-alerts/slack-admission-message.png
  nginx.conf
Labels: documentation

#643 Moving 'Enforcer Options' doc to 'Installation' bucket
  content/chainguard/chainguard-enforce/installation/configure-enforcer-options-during-installation.md
  nginx.conf
Labels: documentation, enhancement, enforce
