Repository chainguard-dev/edu, pull requests merged in 2023-08, with the labels that each got.

#894 add image digests video
  content/chainguard/chainguard-images/videos/container-image-digests.md
Labels: Q3 2023 Project

#902 UX updates to code snippets, option to remove right nav
  assets/js/snippets.js
  content/software-security/secure-software-development/minimum-attestation-references.md
  content/software-security/secure-software-development/ssdf.md
  layouts/wide/single.html
Labels: Q3 2023 Project, platform development

#896 Software Vulnerability Remediation -- Article
  content/software-security/cves/cve-intro.md
  content/software-security/cves/cve-remediation.md
Labels: Q3 2023 Project

#910 Updating Wollfi with Dockerfiles guide
  content/open-source/wolfi/wolfi-with-dockerfiles.md
Labels: images

#908 adding getting started w/ Postgres image guide
  content/chainguard/chainguard-images/reference/mariadb/getting-started-mariadb/index.md
  content/chainguard/chainguard-images/reference/postgres/getting-started-postgres/index.md
  content/chainguard/chainguard-images/reference/postgres/getting-started-postgres/pg-demo-success-1.png
  content/chainguard/chainguard-images/reference/postgres/getting-started-postgres/pg-demo-success-2.png
Labels: documentation, Q3 2023 Project, images

#907 Fix error on cve-remediation.md
  content/software-security/cves/cve-remediation.md
Labels: bug, Q3 2023 Project

#904 Add CISA, KEV Catalog, NVD to glossary
  content/software-security/glossary.md
Labels: Q3 2023 Project

#926 Remove Console MDs 🧹
  content/ui/enforce.md
  content/ui/group.md
  content/ui/inspect.md
  content/ui/install.md
  content/ui/policy.md
  content/ui/prepare.md
  content/ui/prerequisites.md
  content/ui/test.md
Labels: Q3 2023 Project

#960 Add Images Video on using the Static Base Image
  content/chainguard/chainguard-images/videos/static-base-image.md
Labels: documentation
