Repository chainguard-dev/edu, pull requests merged in 2024-06, with the labels that each got.

#1598 docs: fix typo on github action
  content/chainguard/chainguard-registry/authenticating/index.md
Labels: documentation

#1622 adding redirects for Enforce events docs
  nginx.conf
Labels: documentation, enforce

#1585 Getting Started with the nginx Chainguard Image Tutorial
  content/chainguard/chainguard-images/getting-started/nginx/index.md
Labels: documentation, 24f

#1621 STIG explainer doc
  content/chainguard/chainguard-images/working-with-images/image-stigs.md
Labels: documentation, images, 24f

#1624 Intro grype
  assets/scss/common/_custom.scss
  content/chainguard/chainguard-images/working-with-images/scanners/_index.md
  content/chainguard/chainguard-images/working-with-images/scanners/grype-tutorial/grype_html_output.png
  content/chainguard/chainguard-images/working-with-images/scanners/grype-tutorial/index.md
  layouts/shortcodes/blurb/cvss.html
Labels: DevRel, 24f

#1635 adding chainctl install instructions for Windows
  content/chainguard/administration/how-to-install-chainctl.md
Labels: documentation, 24f
