Repository chainguard-dev/edu, pull requests merged in 2024-03, with the labels that each got.

#1403 adding doc on Unique Tags
  content/chainguard/chainguard-images/unique-tags/index.md
  content/chainguard/chainguard-images/unique-tags/unique-tags-1.png
  content/chainguard/chainguard-images/unique-tags/unique-tags-2.png
Labels: documentation, images, 24b

#1417 adding FAQ entry regarding Wolfi package changes
  content/chainguard/chainguard-images/faq.md
Labels: documentation, images, 24b

#1422 adding blurb about Wolfi Packages to Product Release Lifecycle doc
  content/chainguard/chainguard-images/fips-images.md
  content/chainguard/chainguard-images/versions.md
Labels: documentation, images, 24b

#1456 updating Unique Tags screenshot to reflect customer experience
  content/chainguard/chainguard-images/images-features/unique-tags/index.md
  content/chainguard/chainguard-images/images-features/unique-tags/unique-tags-2.png
Labels: documentation, images

#1457 Add documentation on verifying Images and other attestations
  content/chainguard/chainguard-images/verifying-chainguard-images-and-metadata-signatures-with-cosign.md
Labels: documentation

#1454 Fix some inconsistencies in the IAM examples.
  content/chainguard/administration/iam-groups/identity-examples/aws-identity.md
  content/chainguard/administration/iam-groups/identity-examples/bitbucket-identity.md
  content/chainguard/administration/iam-groups/identity-examples/buildkite-identity.md
  content/chainguard/administration/iam-groups/identity-examples/github-identity/index.md
  content/chainguard/administration/iam-groups/identity-examples/gitlab-identity.md
  content/chainguard/administration/iam-groups/identity-examples/jenkins-identity/index.md
Labels: documentation

#1462 Doc on how Chainguard Images are tested
  content/chainguard/chainguard-images/images-testing.md
Labels: documentation, images

#1467 IAM Updates - batch 1
  content/chainguard/administration/custom-idps/azure-ad/index.md
  content/chainguard/administration/custom-idps/custom-idps/index.md
  content/chainguard/administration/custom-idps/okta/index.md
  content/chainguard/administration/custom-idps/ping-id/index.md
  content/chainguard/administration/how-to-install-chainctl.md
  content/chainguard/administration/iam-groups/how-to-manage-iam-groups-in-chainguard.md
  content/chainguard/administration/iam-organizations/_index.md
  content/chainguard/administration/iam-organizations/assumable-ids.md
  content/chainguard/administration/iam-organizations/how-to-manage-iam-organizations-in-chainguard.md
  content/chainguard/administration/iam-organizations/identity-examples/_index.md
  content/chainguard/administration/iam-organizations/identity-examples/aws-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/bitbucket-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/buildkite-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/github-identity/actions-new-workflow.png
  content/chainguard/administration/iam-organizations/identity-examples/github-identity/actions-run-workflow.png
  content/chainguard/administration/iam-organizations/identity-examples/github-identity/actions-workflow-output.png
  content/chainguard/administration/iam-organizations/identity-examples/github-identity/index.md
  content/chainguard/administration/iam-organizations/identity-examples/gitlab-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/jenkins-identity/index.md
  content/chainguard/administration/iam-organizations/identity-examples/jenkins-identity/jenkins-job-parameter.png
  content/chainguard/administration/iam-organizations/identity-examples/jenkins-identity/jenkins-oidc-connect-config.png
  content/chainguard/administration/iam-organizations/identity-examples/jenkins-identity/jenkins-oidc-credential.png
  content/chainguard/administration/iam-organizations/overview-of-enforce-iam-model.md
  content/chainguard/administration/iam-organizations/rolebinding-terraform-gh/index.md
  content/chainguard/administration/iam-organizations/rolebinding-terraform-gh/login-flow.png
  content/chainguard/administration/iam-organizations/verified-orgs.md
  content/chainguard/chainguard-images/comparing-images/using-the-image-diff-api.md
  content/chainguard/chainguard-images/images-features/using-the-tag-history-api.md
  content/chainguard/chainguard-registry/authenticating/index.md
  nginx.conf
Labels: documentation

#1455 Add a keycloak ID example
  content/chainguard/administration/iam-groups/identity-examples/keycloak-identity.md
Labels: documentation

#1477 Move example to fit with new structure
  content/chainguard/administration/iam-organizations/identity-examples/keycloak-identity.md
Labels: documentation

#1478 adding redirect for keycloak move
  content/chainguard/administration/iam-organizations/identity-examples/keycloak-identity.md
Labels: documentation

#1468 Added a Nexus setup guide and fixed 2 small mistakes in Artifactory
  content/chainguard/chainguard-registry/artifactory-pull-through/index.md
  content/chainguard/chainguard-registry/nexus-pull-through/index.md
  content/chainguard/chainguard-registry/nexus-pull-through/nexus-1.png
  content/chainguard/chainguard-registry/nexus-pull-through/nexus-2.png
Labels: documentation
