Repository chainguard-dev/edu, pull requests merged in 2024-08, with the labels that each got.

#1727 Updating Wolfi with Dockerfiles guide
  content/open-source/wolfi/wolfi-with-dockerfiles.md
Labels: 24h

#1730 Fixing broken links in Academy
  content/chainguard/administration/custom-idps/custom-idps/index.md
  content/chainguard/administration/iam-organizations/assumable-ids.md
  content/chainguard/administration/iam-organizations/identity-examples/aws-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/buildkite-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/github-identity/index.md
  content/chainguard/administration/iam-organizations/identity-examples/jenkins-identity/index.md
  content/chainguard/chainguard-images/faq.md
  content/chainguard/chainguard-images/getting-started/pytorch/index.md
  content/chainguard/chainguard-registry/authenticating/index.md
  content/open-source/sigstore/cosign/how-to-sign-blobs-with-cosign.md
Labels: documentation, 24h

#1720 adding debugging details to migration overview
  content/chainguard/chainguard-images/working-with-images/compiled-programs.md
  content/chainguard/migration/migrations-overview.md
Labels: 24g

#1728 Academy glowup
  assets/scss/common/_custom.scss
  assets/scss/common/_fontfamilies.scss
  assets/scss/common/_resets.scss
  assets/scss/common/_theming.scss
  assets/scss/righthand.scss
  config/_default/menus/menus.en.toml
  layouts/index.html
  layouts/partials/footer/footer.html
  layouts/partials/sidebar/auto-collapsible-menu.html
  layouts/partials/sidebar/docs-toc.html
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon.ico
  static/fonts/bw-fusiona.woff2
  static/fonts/lato/lato-bold-normal-latin.woff2
  static/fonts/lato/lato-regular-italic-latin.woff2
  static/fonts/lato/lato-regular-normal-latin.woff2
  static/fonts/space-mono-regular-normal-latin.woff2
  static/iconography/blue/linky.svg
  static/iconography/linky.svg
  static/iconography/socials/github.svg
  static/iconography/socials/linkedin.svg
  static/iconography/socials/x.svg
  static/iconography/socials/youtube.svg
  static/logos/3d-linky.png
  static/logos/3d-logo.svg
  static/search-dark.svg
  static/search.svg
Labels: enhancement, platform development, 24h

#1714 Adding new Security Advisories content to the Academy
  content/chainguard/chainguard-images/working-with-images/security-advisories/_index.md
  content/chainguard/chainguard-images/working-with-images/security-advisories/how-chainguard-issues/advisories-page.png
  content/chainguard/chainguard-images/working-with-images/security-advisories/how-chainguard-issues/index.md
  content/chainguard/chainguard-images/working-with-images/security-advisories/how-chainguard-issues/nvd-analyze.png
  content/chainguard/chainguard-images/working-with-images/security-advisories/how-to-use/index.md
  content/chainguard/chainguard-images/working-with-images/security-advisories/how-to-use/sec-adv-A.png
  content/chainguard/chainguard-images/working-with-images/security-advisories/how-to-use/sec-adv-B.png
  content/chainguard/chainguard-images/working-with-images/security-advisories/how-to-use/sec-adv-C.png
Labels: documentation, 24g

#1743 landing page for working w/ imgs bucket
  content/chainguard/chainguard-images/getting-started/_index.md
  content/chainguard/chainguard-images/working-with-images/_index.md
Labels: documentation, enhancement, 24h

#1745 Make monospace links in dark mode distinguishable as links
  assets/scss/common/_custom.scss
Labels: 24h

#1746 Updating console URL in docs
  content/chainguard/administration/custom-idps/azure-ad/index.md
  content/chainguard/administration/custom-idps/custom-idps/index.md
  content/chainguard/administration/custom-idps/okta/index.md
  content/chainguard/administration/custom-idps/ping-id/index.md
  content/chainguard/administration/iam-organizations/assumable-ids.md
  content/chainguard/administration/iam-organizations/rolebinding-terraform-gh/index.md
  content/chainguard/administration/manage-chainctl-config.md
  content/chainguard/administration/network-requirements.md
  content/chainguard/chainguard-images/overview.md
  content/chainguard/chainguard-images/working-with-images/images-directory/index.md
  content/chainguard/chainguard-images/working-with-images/retrieve-image-sboms/index.md
  content/chainguard/chainguard-registry/authenticating/index.md
Labels: documentation, 24h

#1752 Updating imgs directory walkthrough with recent console changes
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-1.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-2.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-3.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-4.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-5.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-6.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-7.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-A.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-B.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-C-box.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-D.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-E.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-F.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-G.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-H.png
  content/chainguard/chainguard-images/working-with-images/images-directory/imgs-dir-I.png
  content/chainguard/chainguard-images/working-with-images/images-directory/index.md
Labels: documentation, enhancement, images, 24h

#1758 Update footer menu items
  config/_default/menus/menus.en.toml
Labels: 24h

#1761 Remove Inky references in Comic
  content/software-security/comics/_index.md
  content/software-security/comics/fighting-vulnerabilities/index.md
  content/software-security/comics/fighting-vulnerabilities/seacuring-software-ep1.png
Labels: 24h

#1767 inky ==> linky update
  content/chainguard/administration/custom-idps/azure-ad/index.md
  content/chainguard/administration/custom-idps/ping-id/index.md
  content/chainguard/administration/iam-organizations/how-to-manage-iam-organizations-in-chainguard.md
  content/chainguard/administration/iam-organizations/rolebinding-terraform-gh/index.md
  content/chainguard/chainguard-images/getting-started/nginx/index.md
  content/chainguard/chainguard-images/getting-started/python.md
  content/chainguard/chainguard-images/getting-started/ruby.md
  content/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/index.md
  content/open-source/sbom/getting-started-openvex-vexctl.md
Labels: documentation, enhancement, 24h

#1771 Updating custom IDPs doc, #2
  content/chainguard/administration/custom-idps/custom-idps/cg-email-signin-24.png
  content/chainguard/administration/custom-idps/custom-idps/cg-org-signin-24.png
  content/chainguard/administration/custom-idps/custom-idps/cg-signin-24-box.png
  content/chainguard/administration/custom-idps/custom-idps/chainguard-email-sign-in.png
  content/chainguard/administration/custom-idps/custom-idps/chainguard-org-sign-in.png
  content/chainguard/administration/custom-idps/custom-idps/chainguard-sign-in.gif
  content/chainguard/administration/custom-idps/custom-idps/index.md
Labels: documentation, enhancement, 24h

#1760 Block quote color
  assets/scss/common/_custom.scss
  assets/scss/common/_theming.scss
Labels: 24h

#1723 Getting Started with the C/C++ Chainguard Image
  content/chainguard/chainguard-images/getting-started/c/index.md
Labels: 24h

#1775 fixes to custom IDPs doc
  content/chainguard/administration/custom-idps/custom-idps/index.md
Labels: documentation, 24h

#1779 Tier changes, part 2/3
  content/chainguard/administration/custom-idps/custom-idps/index.md
  content/chainguard/chainguard-images/how-to-use-chainguard-images.md
  content/chainguard/chainguard-images/working-with-images/images-directory/index.md
  content/chainguard/chainguard-images/working-with-images/retrieve-image-sboms/index.md
  content/chainguard/chainguard-images/working-with-images/security-advisories/how-to-use/index.md
  content/chainguard/chainguard-registry/pull-through-guides/artifact-registry-pull-through/index.md
  content/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/index.md
  content/chainguard/chainguard-registry/pull-through-guides/cloudsmith-pull-through/index.md
  content/chainguard/chainguard-registry/pull-through-guides/nexus-pull-through/index.md
  content/open-source/sbom/getting-started-openvex-vexctl.md
  content/open-source/sigstore/policy-controller/policies/chainguard-enforce-policy-examples.md
  layouts/partials/rumble-comparison.html
Labels: 24h

#1781 Add compliance content for PCI DSS 4.0
  content/software-security/compliance/pci-dss-4/_index.md
  content/software-security/compliance/pci-dss-4/intro-pci-dss-4.md
  content/software-security/compliance/pci-dss-4/pci-dss-chainguard.md
  content/software-security/compliance/pci-dss-4/pci-dss-practices.md
Labels: documentation

#1783 Modifying STIGs overview to include checklist download
  content/chainguard/chainguard-images/working-with-images/image-stigs.md
Labels: documentation, enhancement, 24h
