Repository chainguard-dev/edu, pull requests merged in 2024-09, with the labels that each got.

#1799 Updated draft of Trevor's glibc vs musl draft
  content/chainguard/chainguard-images/working-with-images/images-compiled-programs/_index.md
  content/chainguard/chainguard-images/working-with-images/images-compiled-programs/compiled-programs.md
  content/chainguard/chainguard-images/working-with-images/images-compiled-programs/glibc-vs-musl.md
Labels: 24i

#1801 Artifactory pull thru guide update
  content/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/artifactory-5.png
  content/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/index.md
Labels: documentation, enhancement, 24i

#1823 rumble: refactor to use vuln scan results from `prod-enforce`
  .github/workflows/rumble-vulnerability-data.yaml
  data/rumble.json
  tools/rumble/cmd/image_csvs.go
  tools/rumble/cmd/legacy_csv.go
  tools/rumble/cmd/options.go
  tools/rumble/cmd/vulns.go
  tools/rumble/go.mod
  tools/rumble/pkg/bigquery/bigquery.go
  tools/rumble/pkg/bigquery/queries.go
  tools/rumble/pkg/cloudstorage/cloudstorage.go
Labels: bug, go, 24i

#1817 fix inky to linky in wolfi intro
  content/open-source/wolfi/wolfi-with-dockerfiles.md
Labels: documentation
