Repository chainguard-dev/edu, pull requests merged in 2024-01, with the labels that each got.

#1263 adding doc on working with security advisories
  content/chainguard/chainguard-images/cve-risk.md
  content/chainguard/chainguard-images/security-advisories/index.md
  content/chainguard/chainguard-images/security-advisories/sec-adv-A.png
  content/chainguard/chainguard-images/security-advisories/sec-adv-B.png
  content/chainguard/chainguard-images/security-advisories/sec-adv-C.png
Labels: documentation, images

#1306 Add page explaining the image diff api
  content/chainguard/chainguard-images/using-the-image-diff-api.md
Labels: 24a

#1319 adding doc on Chainguard Terraform provider
  content/chainguard/administration/iam-groups/rolebinding-terraform-gh/index.md
  content/chainguard/administration/terraform-provider/index.md
  content/chainguard/administration/terraform-provider/tf-diagram.png
Labels: documentation, 24a
