Repository chainguard-dev/edu, pull requests merged in 2024-07, with the labels that each got.

#1669 adding doc on custom certs with incert
  content/chainguard/chainguard-images/working-with-images/incert-custom-certs.md
Labels: 24f, 24g

#1645 add docs for Artifact Registry pull through
  content/chainguard/chainguard-registry/authenticating/index.md
  content/chainguard/chainguard-registry/overview.md
  content/chainguard/chainguard-registry/pull-through-guides/_index.md
  content/chainguard/chainguard-registry/pull-through-guides/artifact-registry-pull-through/Google-Artifact-Registry-1.png
  content/chainguard/chainguard-registry/pull-through-guides/artifact-registry-pull-through/Google-Artifact-Registry-2.png
  content/chainguard/chainguard-registry/pull-through-guides/artifact-registry-pull-through/Google-Secret-Manager-1.png
  content/chainguard/chainguard-registry/pull-through-guides/artifact-registry-pull-through/index.md
  content/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/artifactory-1.png
  content/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/artifactory-2.png
  content/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/artifactory-3.png
  content/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/artifactory-4.png
  content/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/index.md
  content/chainguard/chainguard-registry/pull-through-guides/nexus-pull-through/index.md
  content/chainguard/chainguard-registry/pull-through-guides/nexus-pull-through/nexus-1.png
  content/chainguard/chainguard-registry/pull-through-guides/nexus-pull-through/nexus-2.png
Labels: 24f, 24g

#1687 incorportaing getting started instructions to STIG doc
  content/chainguard/chainguard-images/working-with-images/image-stigs.md
Labels: documentation, 24g

#1674 Add 301s for image reference pages
  content/chainguard/administration/iam-organizations/identity-examples/gitlab-identity.md
  content/chainguard/administration/network-requirements.md
  content/chainguard/chainguard-images/_index.md
  content/chainguard/chainguard-images/debugging-distroless-images.md
  content/chainguard/chainguard-images/faq.md
  content/chainguard/chainguard-images/getting-started/go.md
  content/chainguard/chainguard-images/getting-started/laravel.md
  content/chainguard/chainguard-images/getting-started/nemo/index.md
  content/chainguard/chainguard-images/getting-started/nginx/index.md
  content/chainguard/chainguard-images/getting-started/node.md
  content/chainguard/chainguard-images/getting-started/pytorch-cuda/index.md
  content/chainguard/chainguard-images/getting-started/ruby.md
  content/chainguard/chainguard-images/how-to-use-chainguard-images.md
  content/chainguard/chainguard-images/images-testing.md
  content/chainguard/chainguard-images/overview.md
  content/chainguard/chainguard-images/recommended-practices/considerations-for-image-updates.md
  content/chainguard/chainguard-images/recommended-practices/false-results.md
  content/chainguard/chainguard-images/working-with-images/images-directory/index.md
  content/chainguard/chainguard-images/working-with-images/retrieve-image-sboms/index.md
  content/chainguard/chainguard-images/working-with-images/scanners/grype-tutorial/index.md
  content/chainguard/chainguard-registry/authenticating/index.md
  content/chainguard/migration/migrating-php.md
  content/chainguard/migration/migrating-python.md
  content/chainguard/migration/migrating-to-chainguard-images.md
  content/open-source/build-tools/apko/getting-started-with-apko.md
  content/open-source/wolfi/_index.md
  content/open-source/wolfi/overview.md
  content/open-source/wolfi/wolfi-with-dockerfiles.md
  data/notices.yaml
  layouts/index.html
  layouts/shortcodes/blurb/images-advanced.html
  nginx.conf
Labels: 24g

#1693 removing EAP ref from STIGs doc
  content/chainguard/chainguard-images/working-with-images/image-stigs.md
Labels: documentation, 24g

#1697 Fix redirects
  content/chainguard/administration/custom-idps/custom-idps/index.md
  content/chainguard/administration/iam-organizations/assumable-ids.md
  content/chainguard/administration/iam-organizations/identity-examples/aws-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/bitbucket-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/buildkite-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/gitlab-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/keycloak-identity.md
  content/chainguard/chainguard-images/getting-started/cilium/index.md
  content/chainguard/chainguard-images/getting-started/go.md
  content/chainguard/chainguard-images/getting-started/istio.md
  content/chainguard/chainguard-images/getting-started/laravel.md
  content/chainguard/chainguard-images/getting-started/mariadb/index.md
  content/chainguard/chainguard-images/getting-started/nemo/index.md
  content/chainguard/chainguard-images/getting-started/nginx/index.md
  content/chainguard/chainguard-images/getting-started/node.md
  content/chainguard/chainguard-images/getting-started/php.md
  content/chainguard/chainguard-images/getting-started/postgres/index.md
  content/chainguard/chainguard-images/getting-started/python.md
  content/chainguard/chainguard-images/getting-started/pytorch-cuda/index.md
  content/chainguard/chainguard-images/getting-started/ruby.md
Labels: 24g

#1698 Cloudsmith pull through doc
  content/chainguard/chainguard-registry/pull-through-guides/artifact-registry-pull-through/index.md
  content/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/index.md
  content/chainguard/chainguard-registry/pull-through-guides/cloudsmith-pull-through/cloudsmith-1.png
  content/chainguard/chainguard-registry/pull-through-guides/cloudsmith-pull-through/cloudsmith-2.png
  content/chainguard/chainguard-registry/pull-through-guides/cloudsmith-pull-through/cloudsmith-3.png
  content/chainguard/chainguard-registry/pull-through-guides/cloudsmith-pull-through/cloudsmith-4.png
  content/chainguard/chainguard-registry/pull-through-guides/cloudsmith-pull-through/cloudsmith-5.png
  content/chainguard/chainguard-registry/pull-through-guides/cloudsmith-pull-through/index.md
  content/chainguard/chainguard-registry/pull-through-guides/nexus-pull-through/index.md
Labels: 24g

#1705 Adding Migration Guide 'Overview'
  content/chainguard/migration/migrations-overview.md
Labels: documentation, images, 24g

#1710 Increase navbar display depth
  content/chainguard/chainguard-images/working-with-images/scanners/grype-tutorial/index.md
  content/chainguard/chainguard-images/working-with-images/scanners/trivy-tutorial/index.md
  layouts/partials/sidebar/auto-collapsible-menu.html
Labels: 24g

#1719 Updating many links
  content/chainguard/administration/custom-idps/azure-ad/index.md
  content/chainguard/administration/custom-idps/custom-idps/index.md
  content/chainguard/administration/custom-idps/okta/index.md
  content/chainguard/administration/custom-idps/ping-id/index.md
  content/chainguard/administration/iam-organizations/assumable-ids.md
  content/chainguard/administration/iam-organizations/how-to-manage-iam-organizations-in-chainguard.md
  content/chainguard/administration/iam-organizations/identity-examples/aws-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/bitbucket-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/buildkite-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/github-identity/index.md
  content/chainguard/administration/iam-organizations/identity-examples/gitlab-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/jenkins-identity/index.md
  content/chainguard/administration/iam-organizations/identity-examples/keycloak-identity.md
  content/chainguard/administration/iam-organizations/overview-of-chainguard-iam-model.md
  content/chainguard/administration/iam-organizations/rolebinding-terraform-gh/index.md
  content/chainguard/administration/iam-organizations/verified-orgs.md
  content/chainguard/administration/terraform-provider/index.md
  content/chainguard/chainguard-images/faq.md
  content/chainguard/chainguard-images/overview.md
  content/chainguard/chainguard-images/working-with-images/comparing-images.md
  content/chainguard/chainguard-images/working-with-images/fips-images.md
  content/chainguard/chainguard-images/working-with-images/using-the-tag-history-api.md
  content/chainguard/chainguard-registry/authenticating/index.md
  content/chainguard/migration/migrating-node.md
  content/chainguard/migration/migrating-php.md
  content/chainguard/migration/migrating-to-chainguard-images.md
  content/chainguard/migration/migrations-overview.md
  content/chainguard/migration/porting-apps-to-chainguard/index.md
  content/open-source/build-tools/apko/bazel-rules.md
  content/open-source/build-tools/melange/getting-started-with-melange.md
  content/open-source/sigstore/policy-controller/policies/using-policy-controller-to-verify-signed-chainguard-images.md
  content/open-source/sigstore/rekor/an-introduction-to-rekor.md
Labels: bug, documentation, 24h

#1701 24g minor Academy edits
  content/chainguard/chainguard-images/getting-started/istio.md
  content/chainguard/chainguard-images/getting-started/nginx/index.md
  content/chainguard/chainguard-images/working-with-images/compiled-programs.md
  content/open-source/sigstore/cosign/_index.md
  content/open-source/sigstore/cosign/an-introduction-to-cosign.md
  content/open-source/sigstore/cosign/cosign-manual-way.md
  content/open-source/sigstore/cosign/how-to-install-cosign.md
  content/open-source/sigstore/cosign/how-to-sign-a-container-with-cosign.md
  content/open-source/sigstore/cosign/how-to-sign-an-sbom-with-cosign.md
  content/open-source/sigstore/cosign/how-to-sign-blobs-with-cosign.md
  content/open-source/sigstore/cosign/how-to-verify-file-signatures-with-cosign.md
  content/open-source/slsa/what-is-slsa.md
Labels: documentation
