Repository chainguard-dev/edu, pull requests merged in 2024-02, with the labels that each got.

#1326 Refactor rumble to generate all csv and json files using insights data
  .github/workflows/rumble-cve-data.yaml
  .github/workflows/rumble-vulnerability-data.yaml
  .github/workflows/rumble.yaml
  tools/rumble/bigquery.go
  tools/rumble/cmd/commands.go
  tools/rumble/cmd/image_csvs.go
  tools/rumble/cmd/legacy_csv.go
  tools/rumble/cmd/options.go
  tools/rumble/cmd/vulns.go
  tools/rumble/go.mod
  tools/rumble/go.sum
  tools/rumble/grype.go
  tools/rumble/main.go
  tools/rumble/pkg/bigquery/bigquery.go
  tools/rumble/pkg/bigquery/queries.go
  tools/rumble/pkg/cloudstorage/cloudstorage.go
  tools/rumble/pkg/grype/grype.go
  tools/rumble/pkg/grype/queries.go
Labels: 24a

#1340 updating getting started w/ apko guide
  content/open-source/apko/getting-started-with-apko.md
Labels: documentation, enhancement, 24a

#1334 Update network requirements page for Images only
  content/chainguard/administration/network-requirements.md
Labels: 24a

#1357 Adding doc on FIPS Images
  content/chainguard/chainguard-images/fips-images.md
Labels: documentation, images

#1361 Video landing page, index.html, header
  content/chainguard/chainguard-images/_index.md
  content/chainguard/chainguard-images/videos/_index.md
  layouts/index.html
  layouts/partials/head/script-header.html
Labels: 24b

#1368 adding doc on setting up pull through cache with Artifactory
  content/chainguard/chainguard-registry/artifactory-pull-through/artifactory-1.png
  content/chainguard/chainguard-registry/artifactory-pull-through/artifactory-2.png
  content/chainguard/chainguard-registry/artifactory-pull-through/artifactory-3.png
  content/chainguard/chainguard-registry/artifactory-pull-through/artifactory-4.png
  content/chainguard/chainguard-registry/artifactory-pull-through/index.md
Labels: documentation, images, 24b

#1374 Add cache-control header to nginx for html files
  nginx.conf
Labels: 24b

#1384 Debian compatibility
  content/chainguard/chainguard-images/migration-guides/debian-compatibility.md
Labels: 24b

#1391 Add alpine, red hat, ubuntu compatibility pages
  content/chainguard/chainguard-images/migration-guides/debian-compatibility.md
  content/chainguard/migration-guides/_index.md
  content/chainguard/migration-guides/alpine-compatibility.md
  content/chainguard/migration-guides/debian-compatibility.md
  content/chainguard/migration-guides/red-hat-compatibility.md
  content/chainguard/migration-guides/ubuntu-compatibility.md
  tools/compatibility-pages/compare.py
Labels: 24b
