Repository chainguard-dev/edu, pull requests merged in 2024-05, with the labels that each got.

#1554 updating IAM docs to reflect new nomenclature
  content/chainguard/administration/iam-organizations/assumable-ids.md
  content/chainguard/administration/iam-organizations/identity-examples/aws-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/bitbucket-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/buildkite-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/github-identity/index.md
  content/chainguard/administration/iam-organizations/identity-examples/gitlab-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/jenkins-identity/index.md
  content/chainguard/administration/iam-organizations/identity-examples/keycloak-identity.md
  content/chainguard/administration/iam-organizations/rolebinding-terraform-gh/index.md
  content/chainguard/administration/terraform-provider/index.md
Labels: documentation

#1557 fixing broken alias + updating lastmod field from my last PR
  content/chainguard/administration/iam-organizations/assumable-ids.md
  content/chainguard/administration/iam-organizations/identity-examples/aws-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/bitbucket-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/buildkite-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/github-identity/index.md
  content/chainguard/administration/iam-organizations/identity-examples/gitlab-identity.md
  content/chainguard/administration/iam-organizations/identity-examples/jenkins-identity/index.md
  content/chainguard/administration/iam-organizations/identity-examples/keycloak-identity.md
  content/chainguard/administration/iam-organizations/rolebinding-terraform-gh/index.md
  content/chainguard/administration/terraform-provider/index.md
  content/chainguard/chainguard-images/working-with-images/retrieve-image-sboms/index.md
Labels: documentation

#1569 Include subpath in iam-groups -> iam-orgs redirect.
  nginx.conf
Labels: bug

#1577 Resolve #1571
  content/open-source/sbom/getting-started-openvex-vexctl.md
Labels: 24e

#1579 migration guide landing page
  content/chainguard/migration/_index.md
  static/icon-arrows.svg
Labels: 24e

#1590 image-copy-gcp events doc + deleting enforce events
  content/chainguard/administration/cloudevents/create-github-issues/github-issue.png
  content/chainguard/administration/cloudevents/create-github-issues/google-cloud-logs.png
  content/chainguard/administration/cloudevents/create-github-issues/index.md
  content/chainguard/administration/cloudevents/create-jira-issues/google-cloud-logs.png
  content/chainguard/administration/cloudevents/create-jira-issues/index.md
  content/chainguard/administration/cloudevents/create-jira-issues/jira-issue.png
  content/chainguard/administration/cloudevents/create-slack-alerts/index.md
  content/chainguard/administration/cloudevents/create-slack-alerts/slack-admission-message.png
  content/chainguard/administration/cloudevents/events-reference.md
  content/chainguard/administration/cloudevents/image-copy-gcr/gcp-events-1.png
  content/chainguard/administration/cloudevents/image-copy-gcr/index.md
Labels: documentation, images, enforce

#1594 Fix terminal chainctl install page path
  layouts/partials/terminal.html
Labels: bug
