Repository chainguard-dev/edu, pull requests merged in 2024-10, with the labels that each got.

#1836 Fix typo in SBOM section
  content/open-source/sbom/what-is-an-sbom.md
Labels: documentation

#1850 Remove Wolfi community reference
  content/open-source/wolfi/building-a-wolfi-package.md
Labels: documentation

#1853 Adding Shared Responsibility Model Overview
  content/chainguard/chainguard-images/recommended-practices/shared-responsibility-model/csrm-1.png
  content/chainguard/chainguard-images/recommended-practices/shared-responsibility-model/csrm-2.png
  content/chainguard/chainguard-images/recommended-practices/shared-responsibility-model/csrm-3.png
  content/chainguard/chainguard-images/recommended-practices/shared-responsibility-model/csrm-4.png
  content/chainguard/chainguard-images/recommended-practices/shared-responsibility-model/index.md
Labels: documentation, 24j

#1866 adding login details to custom idp docs, centering/adjusting images
  content/chainguard/administration/custom-idps/ms-entra-id/index.md
  content/chainguard/administration/custom-idps/okta/index.md
  content/chainguard/administration/custom-idps/okta/okta-2.png
  content/chainguard/administration/custom-idps/okta/okta-3.png
  content/chainguard/administration/custom-idps/okta/okta-6.png
  content/chainguard/administration/custom-idps/ping-id/index.md
Labels: documentation, 24j

#1872 initial fix for FIPS page
  content/chainguard/chainguard-images/working-with-images/fips-images.md
Labels: 24j
