Repository chainguard-dev/edu, pull requests merged in 2025-04, with the labels that each got.

#2148 Improve docs for Java repo manager config
  content/chainguard/libraries/java/build-configuration.md
  content/chainguard/libraries/java/global-configuration.md
  content/chainguard/libraries/java/management.md
Labels: DevRel, 25b

#2157 Adjust Gradle config for Chainguard Libraries for Java
  content/chainguard/libraries/java/build-configuration.md
Labels: documentation, DevRel, 25b

#2158 Improve Maven docs for Chainguard Libraries for Java
  content/chainguard/libraries/java/build-configuration.md
Labels: documentation, DevRel, 25b

#2163 Improve info about MavenGate
  content/chainguard/libraries/faq.md
Labels: documentation, DevRel, 25b

#2164 Improve repo manager docs
  content/chainguard/libraries/java/global-configuration.md
Labels: documentation, DevRel, 25b

#2166 Expand FAQ for Chainguard Libraries
  content/chainguard/libraries/faq.md
Labels: documentation, DevRel, 25b

#2185 Add a docs page for the new chainctl images history command
  content/chainguard/chainctl-usage/_index.md
  content/chainguard/chainctl-usage/chainctl-images-history.md
  content/chainguard/chainctl-usage/chainctl-images.md
Labels: documentation, 25b

#2174 Add docs for Google Artifact Registry with Java libraries
  content/chainguard/libraries/java/global-configuration.md
Labels: documentation, DevRel, 25b

#2181 Correct order in Product Docs navigation
  content/chainguard/administration/_index.md
  content/chainguard/chainctl-usage/_index.md
  content/chainguard/chainctl/_index.md
  content/chainguard/chainguard-images/_index.md
  content/chainguard/chainguard-registry/_index.md
  content/chainguard/libraries/_index.md
  content/chainguard/migration/_index.md
Labels: documentation, DevRel, 25b

#2193 Add init.gradle example
  content/chainguard/libraries/java/build-configuration.md
Labels: documentation, DevRel, 25b

#2194 Adjust to final URL for Chainguard Libraries for Java
  content/chainguard/libraries/java/build-configuration.md
  content/chainguard/libraries/java/global-configuration.md
  content/chainguard/libraries/java/overview.md
Labels: documentation, DevRel, 25b

#2195 Document env variable use with chainctl
  content/chainguard/libraries/access.md
  content/chainguard/libraries/java/build-configuration.md
Labels: documentation, DevRel, 25b

#2210 Add info for Java artifact verification
  content/chainguard/libraries/java/management.md
  content/chainguard/libraries/java/overview.md
Labels: documentation, DevRel, 25b

#2221 Merge chainctl update and version pages
  content/chainguard/chainctl-usage/chainctl-update.md
  content/chainguard/chainctl-usage/chainctl-version-update.md
  content/chainguard/chainctl-usage/chainctl-version.md
Labels: 25b

#2222 chainctl update does not always require admin rights
  content/chainguard/chainctl-usage/chainctl-version-update.md
Labels: 25b
