Repository chainguard-dev/edu, pull requests merged in 2025-03, with the labels that each got.

#2100 Create some new chainctl docs pages
  content/chainguard/chainctl-usage/_index.md
  content/chainguard/chainctl-usage/getting-started-with-chainctl.md
Labels: 25a

#2102 Add docs pages related to chainctl <noun> <verb> forms
  content/chainguard/chainctl-usage/_index.md
  content/chainguard/chainctl-usage/chainctl-events.md
  content/chainguard/chainctl-usage/chainctl-iam.md
  content/chainguard/chainctl-usage/chainctl-images.md
  content/chainguard/chainctl-usage/chainctl-packages.md
  content/chainguard/chainctl-usage/chainctl-update.md
  content/chainguard/chainctl-usage/chainctl-version.md
  content/chainguard/chainctl-usage/getting-started-with-chainctl.md
Labels: 25a

#2125 Fixing timestamps
  content/chainguard/chainctl-usage/chainctl-events.md
  content/chainguard/chainctl-usage/chainctl-iam.md
  content/chainguard/chainctl-usage/chainctl-images.md
  content/chainguard/chainctl-usage/chainctl-packages.md
  content/chainguard/chainctl-usage/chainctl-update.md
  content/chainguard/chainctl-usage/chainctl-version.md
  content/chainguard/chainctl-usage/getting-started-with-chainctl.md
Labels: bug

#2129 Add Chainguard Libraries for Java documentation
  content/chainguard/libraries/_index.md
  content/chainguard/libraries/access.md
  content/chainguard/libraries/faq.md
  content/chainguard/libraries/java/_index.md
  content/chainguard/libraries/java/build-configuration.md
  content/chainguard/libraries/java/global-configuration.md
  content/chainguard/libraries/java/management.md
  content/chainguard/libraries/java/overview.md
  content/chainguard/libraries/overview.md
Labels: documentation, DevRel, 25b

#2141 Improve Chainguard Libraries docs
  content/chainguard/libraries/access.md
  content/chainguard/libraries/overview.md
Labels: documentation, DevRel, 25b

#2146 Add FAQ entry about supply chain attacks on libraries
  content/chainguard/libraries/faq.md
Labels: documentation, 25b

#2149 Clarify libraries token setup and testing
  content/chainguard/libraries/access.md
  content/chainguard/libraries/java/overview.md
Labels: DevRel, 25b

#2142 Add FAQ entry about Chibbies
  content/chainguard/libraries/faq.md
Labels: documentation, DevRel, 25b
